# passbolt_ansible

# Copyright (C) 2019  NeuroForge GmbH & Co.KG <https://neuroforge.de/>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
---
- name: Allow incoming access to the mariadb port 3306 for docker servers and the database ip itself
  ufw:
    rule: allow
    direction: in
    src: "{{ item }}"
    to_port: 3306
  with_items:
    # dont allow connections to the ip directly, ssl is not enforced for all
    # connections (because of Wordpress). We have to make sure this is okay before
    # we open to the outside ip.
    #- "{{ host_ip }}/32"
    - 172.17.0.0/16
    - 172.18.0.0/16