# passbolt_ansible

# Copyright (C) 2019  NeuroForge GmbH & Co.KG <https://neuroforge.de/>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
---
- hosts: all
  vars:
    ansible_ssh_private_key_file: "{{ playbook_dir }}/ssh_keys/root_rsa"
    ansible_user: "rkee"
  gather_facts: False
  tasks:
    - name: "Check if Python is already installed"
      raw: which python3
      register: python_check
      ignore_errors: yes

    - name: "Install Python if not already installed"
      raw: sudo apt update -y && sudo apt install python3 -y && sudo apt install python3-simplejson -y
      when: python_check.rc != 0
- hosts: all
  become: true
  vars:
    ansible_ssh_private_key_file: "{{playbook_dir}}/ssh_keys/root_rsa"
    ansible_user: "rkee"
    
    apt_update_cache: True
    apt_restart_after_dist_upgrade: True
  roles:
    - role: essential-software-setup