# passbolt_ansible

# Copyright (C) 2019  NeuroForge GmbH & Co.KG <https://neuroforge.de/>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
---
- hosts: mariadb
  become: true
  vars:
    ansible_ssh_private_key_file: "{{playbook_dir}}/ssh_keys/root_rsa"
    ansible_user: "rkee"
    
    apt_update_cache: True
    apt_restart_after_dist_upgrade: True
    setup_additional_groups:
      - name: "mysql"
        requires_root_password: True
    setup_additional_users:
      - name: "mysql"
        group: "mysql"
        is_sudo: False
    ssl_cert_dirs:
      - directory: "{{ mariadb_cert_dir }}"
        owner: mysql
        group: mysql
  roles:
    - role: user-setup
    - role: copy-ssl-certs

- hosts: mariadb
  become: true
  vars:
    ansible_ssh_private_key_file: "{{playbook_dir}}/ssh_keys/root_rsa"
    ansible_user: "rkee"
    
    apt_update_cache: True

    mysql_user_home: /home/mysql
    mysql_user_name: mysql
    mysql_user_password: mysql

    mysql_root_password_update: false
    mysql_enabled_on_startup: true

    mysql_config_include_files: 
      - src: "files/mariadb_configs/{{ inventory_hostname }}/99-config.cnf"
        force: yes

    mysql_port: "3306"
    mysql_bind_address: '0.0.0.0'
    mysql_datadir: /var/lib/mysql

    mysql_packages:
      - mariadb-client
      - mariadb-server
      - python3-mysqldb

    overwrite_global_mycnf: true

  roles:
    - role: geerlingguy.mysql
    - role: mariadb-post-setup