---
- hosts: nginx
  become: true
  vars:
    ansible_ssh_private_key_file: "{{playbook_dir}}/ssh_keys/root_rsa"
    ansible_user: "root"
    
  roles:
    - install-nginx
    - install-certbot
    - certbot-run
    - update-nginx-vhosts