all:
  children:
    nginx:
      hosts:
        passbolt_server:
          ansible_host: 95.217.11.108
          host_ip: "{{ ansible_host }}"

          certbot_base_domains_singular:
            - name: "{{ infrastructure_base_domain }}"
          
          certbot_domains_singular:
            - name: "{{ passbolt_domain }}"
          
          certbot_base_domains: "{{ certbot_base_domains_singular }}"
          certbot_domains: "{{ certbot_domains_singular }}"
    passbolt:
      hosts:
        passbolt_server:
          ansible_host: 95.217.11.108
          host_ip: "{{ ansible_host }}"
    mariadb:
      hosts:
        passbolt_server:
          ansible_host: 95.217.11.108
          host_ip: "{{ ansible_host }}"
